### ISSUE TITLE
Links broken in haddocks

### ISSUE THREAD

**Issue by dbaynard** [tomjaguarpaw/bluefin#1]
https://github.com/tomjaguarpaw/bluefin/blob/d88d7df5bc00b22a5019e6d51cd1a08e6f07492d/bluefin/src/Bluefin.hs#L127-L128

Links to Coroutine and Compound are broken on hackage and your site — I haven't checked the rest.

**Comment by dbaynard** [comment]
I'm seeking an excuse to try out [quickstrom](https://quickstrom.io/) and this seems like a suitable case — let me know if you're interested.

**Comment by tomjaguarpaw** [comment]
> I'm seeking an excuse to try out [quickstrom](https://quickstrom.io/) and this seems like a suitable case — let me know if you're interested.

Yes, definitely!
