### ISSUE TITLE
Why two packages instead of a public sub-library?

### ISSUE THREAD

**Issue by michaelpj** [tomjaguarpaw/bluefin#12]
I can't see a good reason not to have `bluefin-internal` as just a public sub-library of `bluefin`, unless it's actually advantageous to be able to mix-and-match versions. Which seems unlikely since AFAICT `bluefin` just re-exports `bluefin-internal`.

**Comment by tomjaguarpaw** [comment]
There will be times I will want to change `bluefin-internal`, for example to remove internals `f` and `g` and just use internal `h` instead (which is a generalization of both), without bumping the version of `bluefin`. Could I do that if `bluefin-internal` was a public sublibrary?

**Comment by tomjaguarpaw** [comment]
Similiarly, there will be times I will want to change `bluefin` (say to expose something previously not exposed) and therefore bump `bluefin` without bumping `bluefin-internal`.

**Comment by michaelpj** [comment]
Hmmm. Yes okay, if you want to a) expose `bluefin-internal` fully, b) version `bluefin-internal` fully following the PVP, c) not bump frequently; then I guess you _do_ want to mix-and-match versions, which means you need two packages.

Personally I would probably just eat the costs, and either not expose `bluefin-internal` until it has settled down a bit, or just accept more major version bumps, but preferences differ.

**Comment by tomjaguarpaw** [comment]
Yes, this was my ultimate conclusion here: https://discourse.haskell.org/t/pvp-compliance-of-internal-modules/6784/7?u=tomjaguarpaw
