### ISSUE TITLE
What's the benefit of "higher-order effects", e.g. local

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/bluefin#15]
Following up from https://github.com/re-xyr/cleff/issues/31#issuecomment-2096089076 and https://github.com/tomjaguarpaw/bluefin/pull/14#issuecomment-2097944270, I don't understand why "higher-order effects" are useful, as opposed to just writing handlers. @re-xyr [clarifies that](https://github.com/re-xyr/cleff/issues/31#issuecomment-2097365379)

> The difference between a higher-order operation and a handler is that the former is an abstraction of the latter, just like how a (first-order) effect operation is an abstraction of a monadic action.

but I still can't think of an example of a higher-order effect that couldn't be implemented just as well as a handler. For example, [`MonadReader` has](https://www.stackage.org/haddock/lts-22.21/mtl-2.3.1/Control-Monad-Reader.html#v:local)

```.hs
local :: (r -> r) -> m a -> m a
```

but why is `local f m` that better than (in Bluefin terms)

```.hs
\reader -> do
    r <- ask reader
    runReader (f r) m
```

**Comment by Lysxia** [comment]
I am also on the confused side. In addition to use cases, it would also be nice to clarify the semantics. By that I mean that cleff and effectful currently just give you unsafe primitives (`toEff`, `withEffToIO`) to deal with them. They are unsafe because they allow you to run a computation outside of the handler for its effects. Is there a safe API, or are there guidelines for how to safely handle higher-order effects?

**Comment by tomjaguarpaw** [comment]
I believe there is a naturality requirement, perhaps `local (m1 >=> m2) = local m1 >=> local m2`? Does that help clarify the semantics?

**Comment by Lysxia** [comment]
I meant a semantics for higher-order effects in general (though I admit it's not a clearly defined question).

I think `local` is well understood enough but also not a great example because it can be implemented as either a handler of the `reinterpret` variety (which in bluefin corresponds to intercepting a handle), or even more simply using state.

**Comment by tomjaguarpaw** [comment]
I think the same condition might generalise to other higher-order effects. For example, there is the notion of "control operator" from [Definition 4 of the Arrow notation paper](https://www.staff.city.ac.uk/~ross/papers/notation.pdf) (although maybe that only works with "order 2" effects, where `m` can appear on the left on an arrow, but only at "order 1").

**Comment by arybczak** [comment]
> They are unsafe because they allow you to run a computation outside of the handler for its effects.

Do you have an example?

**Comment by Lysxia** [comment]
```
{-# LANGUAGE DataKinds, GADTs, ScopedTypeVariables, TypeFamilies, TypeOperators #-}

import Effectful (Eff, runEff, DispatchOf, Dispatch(..))
import Effectful.Dispatch.Dynamic (interpret, localSeqUnlift, send)
import Effectful.Error.Static (runErrorNoCallStack, throwError)
import Effectful.State.Static.Local (evalState, get, put, State)

data Profiling m a where
  Profile :: m () -> Profiling m ()

type instance DispatchOf Profiling = Dynamic

-- Stateful computations where the state is a stateful computation
newtype StateEff es = StateEff (Eff (State (StateEff es) ': es) ())

-- Use localSeqUnlift to smuggle a throwing computation to a pure environment into a put
test :: Eff es ()
test = evalState (StateEff (pure ())) $ do
  interpret
    (\env (Profile m) -> localSeqUnlift env (\unlift -> put (StateEff (unlift m))))
    (runErrorNoCallStack (send (Profile (throwError ()))) >>= \(e :: Either () ()) -> pure ())
  StateEff throw <- get
  throw

main :: IO ()
main = runEff test
```

Runtime error:

```
version (4) /= storageVersion (0)
CallStack (from HasCallStack):
  error, called at src/Effectful/Internal/Env.hs:358:5 in effectful-core-2.3.0.1
```

**Comment by re-xyr** [comment]
@Lysxia I'm happy that you brought up the topic of type safety! It's been on my mind for a long time that cleff needs an API redo of some sort to make it type safe, but I wasn't sure what to do exactly.

I have put some of my ideas [on the `SpEff` repo](https://github.com/re-xyr/speff) -- could you please take a look, specifically with finding type unsafeness in mind? I'm sorry I couldn't put up the documentation on Hackage; I didn't want to pollute the registry with a toy project that I wrote for a talk.

**Comment by arybczak** [comment]
@Lysxia I see. Well, if you're clever enough you can write [unsafeCoerce](https://github.com/haskell-effectful/effectful/blob/0e312c77f49edb5f3d74cb70bf3fc0d9cd1816ff/effectful/tests/EnvTests.hs#L109), it's just that it doesn't work at runtime (as your example doesn't). I thought you had something that worked.

**Comment by evanrelf** [comment]
> I see you gave [my comment](https://github.com/re-xyr/cleff/issues/31#issuecomment-2096523919) a "thumbs down". Is there something you could elaborate on? Are you upset with my lack of understanding, or my suggestion to move the discussion elsewhere?

That was for "I don't understand why `local`, `listen` and `StateM` are useful". I misinterpreted your confusion / lack of understanding as criticism / dismissal of the higher order effects; my bad.

**Comment by evanrelf** [comment]
My understanding is:

Using handlers bakes in specific interpretations of effects into your programs, whereas using higher order effects defers the interpretation of those operations until the end.

I think you could get closer to the behavior of higher order effects if your value-level effects stuff included the handler. Some pseudocode (I don't know `bluefin`):

```diff
 \reader -> do
     r <- ask reader
-    runReader (f r) m
+    run reader (f r) m 
```

**Comment by tomjaguarpaw** [comment]
> I misinterpreted your confusion / lack of understanding as criticism / dismissal of the higher order effects; my bad.

Ah, that's OK. Online communication makes misunderstandings easy.

> Using handlers bakes in specific interpretations of effects into your programs, whereas using higher order effects defers the interpretation of those operations until the end.

Right, that makes sense to me I think I'm comfortable with the idea now.

> Hopefully that makes sense.

Yes, I think the idea makes sense.

I'm still a bit confused about the *purpose* of any form of higher-order effects, especially since handlers can depend on handles, so they need not actually "bake in" specific interpretations.

**Comment by evanrelf** [comment]
Figured I'd mention some further reading:

[`freer-simple`](https://hackage.haskell.org/package/freer-simple) is an example of an older effects library, written by Alexis King, that only supports first order effects, and "emulates" (not sure the best word here) higher order effects by using handlers.

In practice, this is functions like `local`, `catch`, `bracket`, etc; anything taking an `Eff` thing in negative (argument) position.

[Sandy Maguire](https://github.com/isovector) has talked about this, and specifically referenced `freer-simple`, in these articles:

- [Freer, yet Too Costly Higher-order Effects](https://reasonablypolymorphic.com/blog/freer-yet-too-costly/index.html)
- [Polysemy Internals: Freer Interpretations of Higher-Order Effects](https://reasonablypolymorphic.com/blog/freer-higher-order-effects/index.html)

**Comment by evanrelf** [comment]
> I'm still a bit confused about the purpose of any form of higher-order effects, especially since handlers can depend on handles, so they need not actually "bake in" specific interpretations.

Unfortunately I don't know enough about `bluefin` and "handles" here to understand how it differs from libraries like `freer-simple` that bake specific interpretations into programs using concrete handlers ☹️ Sorry

**Comment by tomjaguarpaw** [comment]
Thanks, those references are very helpful. I suppose the reason that I am struggling to understand is that I have almost entirely avoided learning about effect systems, and their difficulties, so far. Until IO-based effect systems (effectful was the first, I believe), they seemed far too complicated to be practical. Given my (lack of) background I see two possible outcomes

1. I am just far too naive about higher-order effects. They are tremendously subtle and Bluefin is going to run aground because I haven't paid attention to them.

2. Authors of previous effect systems have tied themselves up in knots with higher-order effects but for IO-based[^1] effect systems the problems simply don't exist.

Below is how I would implement the "logging catch" example, from the article you linked, "[Polysemy Internals: Freer Interpretations of Higher-Order Effects](https://reasonablypolymorphic.com/blog/freer-higher-order-effects/index.html#)", in Bluefin. In this case it's easy to dynamically configure the behaviour of `catch`. How? Just by passing an argument in!

```.hs
{-# LANGUAGE GHC2021 #-}

import Control.Monad (when)
import Bluefin.Eff
import Bluefin.Exception
import Bluefin.State
import Bluefin.Stream

-- The type of a "dynamic catch handler", also
-- known as a "higher order catch effect"
newtype DynamicCatch es =
  DynamicCatch
  (forall e a.
   (forall e1. Exception e e1 -> Eff (e1 :& es) a) ->
   (e -> Eff es a) ->
   Eff es a)

-- Run the dynamic catch handler
dynamicCatch ::
  DynamicCatch es ->
  (forall e1. Exception e e1 -> Eff (e1 :& es) a) ->
  (e -> Eff es a) ->
  Eff es a
dynamicCatch (DynamicCatch dt) = dt

-- An example of using a dynamic catch handler.
-- The Bool argument determines whether we
-- should throw. We log what we do with a Stream
-- and there's a State in there too, for good measure.
useDynCatch ::
  Bool ->
  (forall es e. e :> es => Stream String e -> DynamicCatch es) ->
  [String]
useDynCatch shouldThrow dyncatch =
  runPureEff $
    fmap fst $ yieldToList $ \y ->
      evalState @Int 0 $ \st -> do
        modify st (+1)
        dynamicCatch (dyncatch y)
          (\ex -> do
              yield y "Running body"
              when shouldThrow (throw ex ())
              modify st (+1)
              yield y "Didn't throw"
          )
          (\() -> do
              yield y "Threw"
          )
        s <- get st
        yield y (show s)

-- Just the standard catch
--
-- ghci> example1 True
-- Running body
-- Threw
-- 1
--
-- ghci> example1 False
-- Running body
-- Didn't throw
-- 2
example1 :: Bool -> IO ()
example1 shouldThrow =
  mapM_ putStrLn $
    useDynCatch shouldThrow (\_ -> DynamicCatch catch)

-- A "logging catch"
--
-- ghci> example2 True
-- Running body
-- Annotated dynamically: unsuccessful
-- Threw
-- 1
--
-- ghci> example2 False
-- Running body
-- Didn't throw
-- Annotated dynamically: successful
-- 2
example2 :: Bool -> IO ()
example2 shouldThrow =
  mapM_ putStrLn $
    useDynCatch shouldThrow $ \y ->
      DynamicCatch $ \body handler ->
        catch
          (\e -> do
              r <- body e
              yield y "Annotated dynamically: successful"
              pure r)
          (\i -> do
              yield y "Annotated dynamically: unsuccessful"
              handler i)
```

[^1]: or possibly "IO-based effect systems with explicit handles"

**Comment by tomjaguarpaw** [comment]
After the discussion on Discourse under [What is a higher-order effect](https://discourse.haskell.org/t/what-is-a-higher-order-effect/10744/34) I now understand the situation better. The point is that the type of `local` should be

```.hs
local ::
  e1 :> es =>
  Reader r e1 ->
  (r -> r) ->
  Eff es a ->
  Eff es a
```

and not

```.hs
```.hs
local ::
  e1 :> es =>
  Reader r e1 ->
  (r -> r) ->
  (forall e. Reader r e -> Eff es a) ->
  Eff es a
```

because we want to locally modify the reader state in a way that will be used in handlers that were defined in terms of the input `Reader`. Here's an example in `effectful`

* https://github.com/haskell-effectful/effectful/blob/a70cf0cbf1fe7adeb5d1a0fef48b90e2aa914052/effectful/tests/ReaderTests.hs#L25-L29

and the Bluefin equivalent

* https://github.com/tomjaguarpaw/bluefin/blob/2dd297f3c988b01453a8cb650f6a28003b88acb6/bluefin-internal/test/Main.hs#L160-L164
